#personal section
personal:
  f_name: Tyler
  l_name: Algigi
  picture: static/img/headshot.jpg
  contact:
    address_one: 4583 Luminary Ave
    phone: (239)404-2255
  email: talgigi@fau.edu
  description:
    - Hello and welcome to my portfolio! I love building amazing software. 
    - I have recently created many projects involving machine learning and artificial intelligence in python. 
    - I am currently in my final year of study for a Bachelors in Computer Science at Florida Atlantic University as well as obatining a certification in Data Science.

# Social section
social:
  github: https://github.com/tyleralgigi
  linkedin: https://www.linkedin.com/in/tyler-algigi/
  twitter: https://twitter.com/TylerAlgigi

experience:
  item0:
    position: Student User Support Services
    company: FAU OIT Help Desk
    from: January 2020
    to: Present
    description:
      - Maintain FAU computer systems and softwares.
      - Work with FAUs active directory, roles and troubleshoot on Windows, Linux, and Mac.
      - Provide technical assistance to customers via phone, email, or ticketing system.
  
  item1:
    position: Technology Department Intern 
    company: Collier County School District
    from: June 2019
    to: August 2019
    description:
      - Support the It team in maintaining hardware, software, and other systems. 
      - Installed new ethernet ports and wireless access points across the school district.
      - Configured and deployed over 1000 Microsoft surface Book and HP ProBooks.
    
  item2:
    position: Equipment Manager
    company: FAU Football Team
    from: March 2018
    to: December 2020
    description:
      - Maintaining inventories of equipment. 
      - Overseeing the fitting and necessary adjustments needs for uniform. 
      - Create bonds with the players and coaches.
  
education:
  item0:
    institution: Florida Atlantic University
    program: B.S. Computer Science
    description: 
      - Database Structures
      - Foundations of CS
      - Principles of Software Engineering
      - Python Programming
  item1:
    institution: Florida Atlantic University
    program: Certification in Data Science
    description: 
      - Stochastic Models for CS
      - Intro to Artificial Intelligence
      - Intro to Deep Learning
      - Intro to Data Science and Analytics

projects:
  item1:
    title: house-prices-regression
    description: A regession algorthm in python to predict the finial price of homes using the Ames Housing dataset.
    link: https://github.com/tyleralgigi/house-prices-regression
    github: https://github.com/tyleralgigi/house-prices-regression
    img: features_importance.png
    tags: [Regression , Python, SKLearn]
  item2:
    title: Traveling Salemen Genetic Algorithm
    description: A genetic algothirm which solves the traveling salesmen problem.
    link: https://github.com/tyleralgigi/TSG-genetic-algo
    github: https://github.com/tyleralgigi/TSG-genetic-algo
    img: tsg_path.png
    tags: [Python, Genetic Algothirm, matplotlib]
  item3:
    title: search-algorithms
    description: Implements serveral search strateiges (BFS, DFS,m A*, minimax) to solve finding the shortest route and play tic tac toe.
    link: https://github.com/tyleralgigi/search-algorithms
    github: https://github.com/tyleralgigi/search-algorithms
    img: map_img.jpg
    tags: [Python, AI]

tools:
  # Consider that the following are fa icons:
  #   https://fontawesome.com/icons?d=gallery&s=brands
  - python
  - react
  - github
  - js
extra_skills:
  - Python - Flask, pandas, NumPy, matplotlib, TensorFlow, Scikit-Learn, SciPy, NLTK, and more 
  - Databases - GraphQL, MQL, SQL
  - Web scraping and web automation using Selenium and BeautifulSoup
  - Flask Web Development
  - Beginner in Javascript/React Native